Updated version of conda to py39_4.12.0
spietras/rules_conda pull request #47
Opened 2022-10-27 21:28 UTC by sfc-gh-zpeng

The main reason for this update is that this version supports M1 mac (MacOSX-arm64).

2022-10-27 23:16 UTC, spietras commented
Cool, thanks for the PR.

What about updating it even further to the newest version, [`22.9.0`](https://github.com/conda/conda/releases/tag/22.9.0) (latest after version numbering change) or [`4.14.0`](https://github.com/conda/conda/releases/tag/4.14.0) (latest before version numbering change)?

2022-10-27 23:26 UTC, spietras requested changes
Can you also change it the same way for `Miniforge`? It's directly below, there should be a version matching `4.12`: https://github.com/conda-forge/miniforge/releases

2022-11-01 23:34 UTC, sfc-gh-zpeng commented
@spietras 

It seems Miniconda is only advertising 4.12.0 in its homepage. That's why I thought that version was the latest one. Also, in the conda channel, the latest version of conda is still 4.12.0. So I wonder if we should keep 4.12.0 for now.

I updated Miniforge version to match Miniconda's (4.12.0-2 , which is the latest 4.12.0 according to the conda-forge channel: https://conda-forge.org/miniforge/).

2022-11-02 12:34 UTC, spietras approved these changes
Great, thanks for contributing to `rules_conda` 💚

2022-11-02 12:35 UTC, merged

2022-11-12 00:10 UTC, sfc-gh-zpeng commented
@spietras does it make sense to push a new release to include this change?

2022-11-12 00:12 UTC, spietras commented
Sure, I will do it soon

2022-11-12 20:42 UTC, spietras commented
@sfc-gh-zpeng Done: https://github.com/spietras/rules_conda/releases/tag/0.2.0